[package]
name = "md4rs-src"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib"]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false


[dependencies]
rand = "0.8.5"
regex = "1.5.4"
queues = "1.1.0"
seq-macro = "0.3"
gnuplot = "0.0.37"
test-case = "1.2.1"
derivative = "2.2.0"
serde_json = "1.0.78"
lazy_static = "1.4.0"
wasm-bindgen = "0.2.79"
phf = { version = "0.10", features = ["macros"] }
onig = { version = "6", default-features = false }
serde = { version = "1.0.136", features = ["derive"] }

