[package]
name = "md4rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib"]


[dependencies]
regex = "1.5.4"
seq-macro = "0.3"
test-case = "1.2.1"
serde_json = "1.0.78"
wasm-bindgen = "0.2.79"
serde = { version = "1.0.136", features = ["derive"] }

